name: Release
on:
  push:
    tags:
      - 'v[0-9]+.*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
      - run: gem build *.gemspec
      - run: gem push *.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_TOKEN }}
